local wk = require 'which-key'
wk.add {
  { '<Leader>a', group = '+Avante' },
  { '<leader>c', group = '+ChatGPT' },
  { '<leader>d', group = '+DAP' },
  { '<leader>f', group = '+File search' },
  { '<leader>g', group = '+Git' },
  { '<leader>h', group = '+Git hunk' },
  { '<leader>i', group = '+Iron' },
  { '<leader>l', group = '+LSP' },
  { '<leader>m', group = '+Arrow' },
  { '<leader>n', group = '+Literate Notes' },
  { '<leader>p', group = '+Parameter swap' },
  { '<Leader>q', group = '+Close' },
  { '<leader>r', group = '+Refactor' },
  { '<leader>R', group = '+Auto-session' },
  { '<leader>s', group = '+Text search' },
  { '<leader>t', group = '+Telescope' },
  { '<leader>T', group = '+ToggleTerm' },
  { '<leader>x', group = '+Trouble' },
  { '<leader>z', group = '+Zen' },
  { '<leader>cd', desc = 'Diagnostics gpt' },
  { '<leader>cs', desc = 'Diagnostics search' },
  { '<leader>[', group = '+prev' },
  { '<leader>]', group = '+next' },
}
